name = "verifiedmodels-cloudflare"
main = "worker.js"
compatibility_date = "2026-09-22"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
enabled = true

[[d1_databases]]
binding = "VM_DB"
database_name = "verifiedmodels-db"
database_id = "61d6b77b-532c-454a-8fe1-645165261ca6"
